name: json_guard
description: A tiny, zero-codegen, runtime-safe JSON parsing helper for Dart & Flutter with precise field-level error messages.
version: 1.0.0
repository: https://github.com/Collins-01/Json-Guard
homepage: https://github.com/Collins-01/Json-Guard
issue_tracker: https://github.com/Collins-01/Json-Guard/issues

topics:
  - json
  - parsing
  - validation
  - type-safety
  - error-handling

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
